version: 2

models:
  - name: customer_360
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

      - name: total_transactions
        tests:
          - not_null

      - name: total_spent
        tests:
          - not_null